#!/usr/bin/env python3
"""
FlowCore Perk Data CSV Extractor
Reads the SavedVariables file generated by FlowCore's '/fc export' command and outputs 'FlowCore_Perks.csv'.
"""

import os
import re
import glob

def find_saved_variables():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    wow_root = os.path.abspath(os.path.join(script_dir, "..", "..", ".."))
    wtf_pattern = os.path.join(wow_root, "WTF", "Account", "*", "SavedVariables", "FlowCore.lua")
    matches = glob.glob(wtf_pattern)
    if matches:
        matches.sort(key=os.path.getmtime, reverse=True)
        return matches[0]
    return None

def extract_csv():
    sv_path = find_saved_variables()
    if not sv_path or not os.path.exists(sv_path):
        print(f"[ERROR] Could not find FlowCore.lua SavedVariables file.")
        print(f"Make sure you logged in, ran '/fc export' (or clicked Export CSV in Config), and ran '/reload'.")
        return

    print(f"Reading SavedVariables from: {sv_path}")
    with open(sv_path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    match = re.search(r'FlowCoreExportDB\s*=\s*\{.*?\["csv"\]\s*=\s*"([^"]+)"', content, re.DOTALL)
    out_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "FlowCore_Perks.csv")
    out_file = os.path.abspath(out_file)

    if match:
        raw_csv = match.group(1)
        unescaped = raw_csv.replace("\\n", "\n").replace('\\"', '"').replace("\\\\", "\\")
        with open(out_file, "w", encoding="utf-8") as out:
            out.write(unescaped)
        print(f"[SUCCESS] Wrote perks CSV to: {out_file}")
    else:
        print("[INFO] Attempting to parse raw perk records from FlowCoreExportDB...")
        perk_records = re.findall(r'\["id"\]\s*=\s*(\d+).*?\["name"\]\s*=\s*"([^"]*)".*?\["category"\]\s*=\s*"([^"]*)".*?\["cat"\]\s*=\s*(\d+)', content, re.DOTALL)
        if perk_records:
            with open(out_file, "w", encoding="utf-8") as out:
                out.write("id,name,cat,category_name\n")
                for r in perk_records:
                    out.write(f'{r[0]},"{r[1]}",{r[3]},"{r[2]}"\n')
            print(f"[SUCCESS] Extracted {len(perk_records)} perks to: {out_file}")
        else:
            print("[ERROR] FlowCoreExportDB table was empty. In game, run '/fc export' and '/reload'.")

if __name__ == "__main__":
    extract_csv()
